'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Main

   '''<summary>
   '''form1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

   '''<summary>
   '''tsmAjax control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents tsmAjax As Global.AjaxControlToolkit.ToolkitScriptManager

   '''<summary>
   '''lblVersionInformation control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblVersionInformation As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''pnlLog control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlLog As Global.System.Web.UI.WebControls.Panel

   '''<summary>
   '''imbShowLogs control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imbShowLogs As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''txtLogName control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtLogName As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''imbLoadLog control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imbLoadLog As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imbManageLogs control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imbManageLogs As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''tweLogName control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents tweLogName As Global.AjaxControlToolkit.TextBoxWatermarkExtender

   '''<summary>
   '''valLogNameRequired control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents valLogNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

   '''<summary>
   '''pnlLogSources control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlLogSources As Global.System.Web.UI.WebControls.Panel

   '''<summary>
   '''pnlLogSourcesHeader control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlLogSourcesHeader As Global.System.Web.UI.WebControls.Panel

   '''<summary>
   '''imbPanelClose control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imbPanelClose As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imbPanelManageLogs control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imbPanelManageLogs As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''pnlLogSourcesContent control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlLogSourcesContent As Global.System.Web.UI.WebControls.Panel

   '''<summary>
   '''tvLogSources control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents tvLogSources As Global.System.Web.UI.WebControls.TreeView

   '''<summary>
   '''pnlSearch control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel

   '''<summary>
   '''MyAccordion control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents MyAccordion As Global.AjaxControlToolkit.Accordion

   '''<summary>
   '''acpBasicSearch control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents acpBasicSearch As Global.AjaxControlToolkit.AccordionPane

   '''<summary>
   '''ddlBasicSearchColumn control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ddlBasicSearchColumn As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''ddlBasicSearchOperator control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ddlBasicSearchOperator As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''txtBasicSearchCriteria control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtBasicSearchCriteria As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''btnStartBasicSearch control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnStartBasicSearch As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnClearBasicSearch control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnClearBasicSearch As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''acpKeywordSearch control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents acpKeywordSearch As Global.AjaxControlToolkit.AccordionPane

   '''<summary>
   '''ddlKeywordSearchColumn control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ddlKeywordSearchColumn As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''txtKeywordSearchCriteria control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtKeywordSearchCriteria As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''btnStartKeywordSearch control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnStartKeywordSearch As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnClearKeywordSearch control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnClearKeywordSearch As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''acpAdvancedSearch control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents acpAdvancedSearch As Global.AjaxControlToolkit.AccordionPane

   '''<summary>
   '''txtGridFilter control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtGridFilter As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''btnStartAdvancedSearch control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnStartAdvancedSearch As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnClearAdvancedSearch control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnClearAdvancedSearch As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''updEvents control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents updEvents As Global.System.Web.UI.UpdatePanel

   '''<summary>
   '''pnlGridOptions control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlGridOptions As Global.System.Web.UI.WebControls.Panel

   '''<summary>
   '''chkUsePaging control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents chkUsePaging As Global.System.Web.UI.WebControls.CheckBox

   '''<summary>
   '''txtEventsPerPage control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtEventsPerPage As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''btnApplyOptions control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnApplyOptions As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''timUpdate control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents timUpdate As Global.System.Web.UI.Timer

   '''<summary>
   '''rblRefreshRate control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents rblRefreshRate As Global.System.Web.UI.WebControls.RadioButtonList

   '''<summary>
   '''btnRefreshGrid control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnRefreshGrid As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''lblLastRefresh control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblLastRefresh As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''gvEvents control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents gvEvents As Global.System.Web.UI.WebControls.GridView

   '''<summary>
   '''lblNoEntries control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblNoEntries As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''lblError control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
End Class
