'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ManageLogSources

   '''<summary>
   '''form1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

   '''<summary>
   '''hypMain control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hypMain As Global.System.Web.UI.WebControls.HyperLink

   '''<summary>
   '''tvLogSources control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents tvLogSources As Global.System.Web.UI.WebControls.TreeView

   '''<summary>
   '''btnDeleteNode control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnDeleteNode As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnMoveNodeUp control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnMoveNodeUp As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnMoveNodeDown control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnMoveNodeDown As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnSaveTree control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnSaveTree As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnReloadTree control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnReloadTree As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''txtSelectedNodeName control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtSelectedNodeName As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''txtSelectedNodePath control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtSelectedNodePath As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''txtSelectedNodeIcon control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtSelectedNodeIcon As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''btnUpdateNode control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnUpdateNode As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''txtNewLogName control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtNewLogName As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''txtNewLogPath control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtNewLogPath As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''txtNewLogIcon control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtNewLogIcon As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''btnAddLogNode control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnAddLogNode As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''txtNewCategoryName control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtNewCategoryName As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''txtNewCategoryIcon control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtNewCategoryIcon As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''btnAddLogCategory control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnAddLogCategory As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''lblStatus control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''lblError control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
End Class
